version: '3'
services:
  app:
    build:
      context: .
    tty: true
    environment:
      - NODE_ENV=${NODE_ENV}
    volumes:
    - ./:/code
    command: sh -c "yarn start"
    ports:
    - "3000:3000"
